version: '3;8'

services:
  dtsistemas:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:5095"
    ports:
      - 5095:5095
    volumes:
      - ./main_project:/main_project
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db-DT
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db-DT

  db-DT:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  background-worker:
    build:
      context: .
    command: sh -c "python manage.py process_tasks"
    volumes:
      - ./main_project:/main_project
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db-DT
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - dtsistemas