# Generated by Django 5.0 on 2023-12-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
